CREATE OR REPLACE TASK TASKS.CLEAN_RETAIL_DATA_TASK
WAREHOUSE = COMPUTE_WH
SCHEDULE = '1 MINUTE'
WHEN (
    SYSTEM$STREAM_HAS_DATA('RAW.CUSTOMERS_STREAM')
    OR SYSTEM$STREAM_HAS_DATA('RAW.PRODUCTS_STREAM')
    OR SYSTEM$STREAM_HAS_DATA('RAW.ORDERS_STREAM')
    OR SYSTEM$STREAM_HAS_DATA('RAW.ORDER_ITEMS_STREAM')
    OR SYSTEM$STREAM_HAS_DATA('RAW.USER_ACTIVITY_STREAM')
)
AS
CALL VALIDATED.SP_CLEAN_RETAIL_STREAM();

CREATE OR REPLACE TASK TASKS.LOAD_CURATED_RETAIL_TASK
WAREHOUSE = COMPUTE_WH
AFTER TASKS.CLEAN_RETAIL_DATA_TASK
AS
CALL CURATED.SP_LOAD_CURATED_RETAIL();

ALTER TASK TASKS.LOAD_CURATED_RETAIL_TASK RESUME;
ALTER TASK TASKS.CLEAN_RETAIL_DATA_TASK RESUME;

INSERT INTO RAW.RAW_CUSTOMERS VALUES
('RC1001','Arun Kumar','Chennai','2024-05-10',CURRENT_TIMESTAMP),
('RC1002','Priya Sharma','Bangalore','2024-04-15',CURRENT_TIMESTAMP),
(NULL,'No ID','Chennai','2024-05-10',CURRENT_TIMESTAMP),
('RC1003',NULL,'Hyderabad','2024-05-10',CURRENT_TIMESTAMP),
('RC1004','Wrong Date','Mumbai','15-04-2024',CURRENT_TIMESTAMP);
