USE ROLE ACCOUNTADMIN;
USE DATABASE RETAIL_COMPANY;

CREATE OR REPLACE TABLE CURATED.DIM_CUSTOMERS (
    CUSTOMER_SK NUMBER AUTOINCREMENT,
    CUSTOMER_ID STRING,
    NAME STRING,
    CITY STRING,
    SIGNUP_DATE DATE,
    EFFECTIVE_START_DATE TIMESTAMP,
    EFFECTIVE_END_DATE TIMESTAMP,
    IS_CURRENT BOOLEAN
);

CREATE OR REPLACE TABLE CURATED.DIM_PRODUCTS (
    PRODUCT_SK NUMBER AUTOINCREMENT,
    PRODUCT_ID STRING,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    PRICE NUMBER(10,2)
);


CREATE OR REPLACE TABLE CURATED.FACT_ORDERS (
    ORDER_SK NUMBER AUTOINCREMENT,
    ORDER_ID STRING,
    CUSTOMER_SK NUMBER,
    ORDER_DATE DATE,
    TOTAL_AMOUNT NUMBER(10,2)
);

CREATE OR REPLACE TABLE CURATED.FACT_ORDER_ITEMS (
    ORDER_ITEM_SK NUMBER AUTOINCREMENT,
    ORDER_ID STRING,
    PRODUCT_SK NUMBER,
    QUANTITY NUMBER
);

CREATE OR REPLACE TABLE CURATED.FACT_USER_ACTIVITY (
    ACTIVITY_SK NUMBER AUTOINCREMENT,
    ACTIVITY_ID STRING,
    CUSTOMER_SK NUMBER,
    ACTIVITY_TYPE STRING,
    ACTIVITY_TIME TIMESTAMP
);


CREATE OR REPLACE PROCEDURE CURATED.SP_LOAD_CURATED_RETAIL()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN


UPDATE CURATED.DIM_CUSTOMERS tgt
SET IS_CURRENT = FALSE,
    EFFECTIVE_END_DATE = CURRENT_TIMESTAMP
FROM VALIDATED.CUSTOMERS src
WHERE tgt.CUSTOMER_ID = src.CUSTOMER_ID
  AND tgt.IS_CURRENT = TRUE
  AND (
        tgt.NAME <> src.NAME
     OR tgt.CITY <> src.CITY
     OR tgt.SIGNUP_DATE <> src.SIGNUP_DATE
  );

INSERT INTO CURATED.DIM_CUSTOMERS (
    CUSTOMER_ID, NAME, CITY, SIGNUP_DATE,
    EFFECTIVE_START_DATE, EFFECTIVE_END_DATE, IS_CURRENT
)
SELECT
    src.CUSTOMER_ID,
    src.NAME,
    src.CITY,
    src.SIGNUP_DATE,
    CURRENT_TIMESTAMP,
    NULL,
    TRUE
FROM VALIDATED.CUSTOMERS src
LEFT JOIN CURATED.DIM_CUSTOMERS tgt
    ON src.CUSTOMER_ID = tgt.CUSTOMER_ID
   AND tgt.IS_CURRENT = TRUE
WHERE tgt.CUSTOMER_ID IS NULL;


MERGE INTO CURATED.DIM_PRODUCTS tgt
USING VALIDATED.PRODUCTS src
ON tgt.PRODUCT_ID = src.PRODUCT_ID
WHEN MATCHED THEN UPDATE SET
    PRODUCT_NAME = src.PRODUCT_NAME,
    CATEGORY = src.CATEGORY,
    PRICE = src.PRICE
WHEN NOT MATCHED THEN INSERT (
    PRODUCT_ID, PRODUCT_NAME, CATEGORY, PRICE
)
VALUES (
    src.PRODUCT_ID, src.PRODUCT_NAME, src.CATEGORY, src.PRICE
);

INSERT INTO CURATED.FACT_ORDERS (
    ORDER_ID, CUSTOMER_SK, ORDER_DATE, TOTAL_AMOUNT
)
SELECT
    o.ORDER_ID,
    dc.CUSTOMER_SK,
    o.ORDER_DATE,
    o.TOTAL_AMOUNT
FROM VALIDATED.ORDERS o
JOIN CURATED.DIM_CUSTOMERS dc
    ON o.CUSTOMER_ID = dc.CUSTOMER_ID
   AND dc.IS_CURRENT = TRUE
WHERE NOT EXISTS (
    SELECT 1 FROM CURATED.FACT_ORDERS f
    WHERE f.ORDER_ID = o.ORDER_ID
);


INSERT INTO CURATED.FACT_ORDER_ITEMS (
    ORDER_ID, PRODUCT_SK, QUANTITY
)
SELECT
    oi.ORDER_ID,
    dp.PRODUCT_SK,
    oi.QUANTITY
FROM VALIDATED.ORDER_ITEMS oi
JOIN CURATED.DIM_PRODUCTS dp
    ON oi.PRODUCT_ID = dp.PRODUCT_ID
WHERE NOT EXISTS (
    SELECT 1 FROM CURATED.FACT_ORDER_ITEMS f
    WHERE f.ORDER_ID = oi.ORDER_ID
);


INSERT INTO CURATED.FACT_USER_ACTIVITY (
    ACTIVITY_ID, CUSTOMER_SK, ACTIVITY_TYPE, ACTIVITY_TIME
)
SELECT
    ua.ACTIVITY_ID,
    dc.CUSTOMER_SK,
    ua.ACTIVITY_TYPE,
    ua.ACTIVITY_TIME
FROM VALIDATED.USER_ACTIVITY ua
JOIN CURATED.DIM_CUSTOMERS dc
    ON ua.CUSTOMER_ID = dc.CUSTOMER_ID
   AND dc.IS_CURRENT = TRUE
WHERE NOT EXISTS (
    SELECT 1 FROM CURATED.FACT_USER_ACTIVITY f
    WHERE f.ACTIVITY_ID = ua.ACTIVITY_ID
);

RETURN 'CURATED LAYER LOADED SUCCESSFULLY (NO NULL DESIGN)';

END;
$$;

SELECT * FROM CURATED.DIM_CUSTOMERS;

SELECT * FROM CURATED.DIM_PRODUCTS;



CALL CURATED.SP_LOAD_CURATED_RETAIL();


SELECT * 
FROM CURATED.FACT_RETAIL
WHERE ACTIVITY_ID IS NOT NULL;



SELECT * 
FROM CURATED.FACT_RETAIL
WHERE ORDER_ID IS NOT NULL;

SELECT * 
FROM CURATED.FACT_RETAIL
WHERE ACTIVITY_ID IS NOT NULL;

SELECT * FROM CURATED.FACT_USER_ACTIVITY;
SELECT * FROM CURATED.FACT_USER_ACTIVITY;
