USE DATABASE RETAIL_COMPANY;

use warehouse compute_wh;


USE SCHEMA ANALYTICAL;

CREATE OR REPLACE VIEW CUSTOMER_360 AS
SELECT
    dc.CUSTOMER_ID,
    dc.NAME,
    dc.CITY,
    dc.SIGNUP_DATE,

    COUNT(DISTINCT fo.ORDER_ID) AS TOTAL_ORDERS,
    COALESCE(SUM(fo.TOTAL_AMOUNT),0) AS TOTAL_SPENT,
    COALESCE(ROUND(AVG(fo.TOTAL_AMOUNT),2),0) AS AVG_ORDER_VALUE,

    MAX(fo.ORDER_DATE) AS LAST_ORDER_DATE,
    MAX(fua.ACTIVITY_TIME) AS LAST_ACTIVITY_TIME,

    COUNT(DISTINCT fua.ACTIVITY_ID) AS TOTAL_ACTIVITIES,


    CASE
        WHEN COALESCE(SUM(fo.TOTAL_AMOUNT),0) >= 50000 THEN 'VIP'
        WHEN COALESCE(SUM(fo.TOTAL_AMOUNT),0) >= 20000 THEN 'HIGH VALUE'
        WHEN COUNT(DISTINCT fo.ORDER_ID) >= 3 THEN 'REGULAR'
        ELSE 'LOW VALUE'
    END AS CUSTOMER_SEGMENT,


    CASE
        WHEN MAX(fo.ORDER_DATE) IS NULL THEN 'NO PURCHASE'
        WHEN DATEDIFF(DAY, MAX(fo.ORDER_DATE), CURRENT_DATE) > 90 THEN 'CHURN RISK'
        ELSE 'ACTIVE'
    END AS CHURN_STATUS

FROM CURATED.DIM_CUSTOMERS dc
LEFT JOIN CURATED.FACT_ORDERS fo
    ON dc.CUSTOMER_SK = fo.CUSTOMER_SK
LEFT JOIN CURATED.FACT_USER_ACTIVITY fua
    ON dc.CUSTOMER_SK = fua.CUSTOMER_SK
WHERE dc.IS_CURRENT = TRUE
GROUP BY
    dc.CUSTOMER_ID,
    dc.NAME,
    dc.CITY,
    dc.SIGNUP_DATE;




    CREATE OR REPLACE VIEW CUSTOMER_SEGMENTATION AS
SELECT
    CUSTOMER_SEGMENT,
    COUNT(*) AS CUSTOMER_COUNT,
    SUM(TOTAL_SPENT) AS TOTAL_REVENUE
FROM ANALYTICAL.CUSTOMER_360
GROUP BY CUSTOMER_SEGMENT
ORDER BY TOTAL_REVENUE DESC;


CREATE OR REPLACE VIEW SALES_INSIGHTS AS
SELECT
    COUNT(DISTINCT ORDER_ID) AS TOTAL_ORDERS,
    SUM(TOTAL_AMOUNT) AS TOTAL_REVENUE,
    ROUND(AVG(TOTAL_AMOUNT),2) AS AVG_ORDER_VALUE
FROM CURATED.FACT_ORDERS;

CREATE OR REPLACE VIEW TOP_PRODUCTS AS
SELECT
    dp.PRODUCT_ID,
    dp.PRODUCT_NAME,
    dp.CATEGORY,
    SUM(foi.QUANTITY) AS TOTAL_SOLD,
    SUM(foi.QUANTITY * dp.PRICE) AS REVENUE
FROM CURATED.FACT_ORDER_ITEMS foi
JOIN CURATED.DIM_PRODUCTS dp
    ON foi.PRODUCT_SK = dp.PRODUCT_SK
GROUP BY
    dp.PRODUCT_ID,
    dp.PRODUCT_NAME,
    dp.CATEGORY
ORDER BY REVENUE DESC;

CREATE OR REPLACE VIEW CHURN_CUSTOMERS AS
SELECT
    CUSTOMER_ID,
    NAME,
    CITY,
    LAST_ORDER_DATE,
    CHURN_STATUS
FROM ANALYTICAL.CUSTOMER_360
WHERE CHURN_STATUS IN ('CHURN RISK','NO PURCHASE');


CREATE OR REPLACE VIEW RECOMMENDATION_LOGIC AS
SELECT
    dc.CUSTOMER_ID,
    dc.NAME,
    dp.CATEGORY,
    COUNT(*) AS PURCHASE_COUNT
FROM CURATED.FACT_ORDERS fo
JOIN CURATED.FACT_ORDER_ITEMS foi
    ON fo.ORDER_ID = foi.ORDER_ID
JOIN CURATED.DIM_PRODUCTS dp
    ON foi.PRODUCT_SK = dp.PRODUCT_SK
JOIN CURATED.DIM_CUSTOMERS dc
    ON fo.CUSTOMER_SK = dc.CUSTOMER_SK
WHERE dc.IS_CURRENT = TRUE
GROUP BY
    dc.CUSTOMER_ID,
    dc.NAME,
    dp.CATEGORY
ORDER BY PURCHASE_COUNT DESC;


SELECT * FROM ANALYTICAL.CUSTOMER_360;
SELECT * FROM ANALYTICAL.CUSTOMER_SEGMENTATION;
SELECT * FROM ANALYTICAL.SALES_INSIGHTS;
SELECT * FROM ANALYTICAL.TOP_PRODUCTS;
SELECT * FROM ANALYTICAL.CHURN_CUSTOMERS;
SELECT * FROM ANALYTICAL.RECOMMENDATION_LOGIC;
