USE DATABASE RETAIL_COMPANY;

USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE FILE FORMAT UTIL.CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE
NULL_IF = ('NULL','null','N/A','',' ');

CREATE OR REPLACE STAGE UTIL.RETAIL_INTERNAL_STAGE
FILE_FORMAT = UTIL.CSV_FORMAT;

CREATE OR REPLACE TABLE RAW.RAW_CUSTOMERS (
    CUSTOMER_ID STRING,
    NAME STRING,
    CITY STRING,
    SIGNUP_DATE STRING,
    LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.RAW_PRODUCTS (
    PRODUCT_ID STRING,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    PRICE STRING,
    LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.RAW_ORDERS (
    ORDER_ID STRING,
    CUSTOMER_ID STRING,
    ORDER_DATE STRING,
    TOTAL_AMOUNT STRING,
    LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.RAW_ORDER_ITEMS (
    ORDER_ITEM_ID STRING,
    ORDER_ID STRING,
    PRODUCT_ID STRING,
    QUANTITY STRING,
    LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.RAW_USER_ACTIVITY (
    ACTIVITY_ID STRING,
    CUSTOMER_ID STRING,
    ACTIVITY_TYPE STRING,
    ACTIVITY_TIME STRING,
    LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
COPY INTO RAW.RAW_CUSTOMERS
FROM '@UTIL.RETAIL_INTERNAL_STAGE/customers.csv'
FILE_FORMAT = UTIL.CSV_FORMAT
ON_ERROR = CONTINUE;

COPY INTO RAW.RAW_PRODUCTS
FROM '@UTIL.RETAIL_INTERNAL_STAGE/products.csv'
FILE_FORMAT = UTIL.CSV_FORMAT
ON_ERROR = CONTINUE;

COPY INTO RAW.RAW_ORDERS
FROM '@UTIL.RETAIL_INTERNAL_STAGE/orders.csv'
FILE_FORMAT = UTIL.CSV_FORMAT
ON_ERROR = CONTINUE;

COPY INTO RAW.RAW_ORDER_ITEMS
FROM '@UTIL.RETAIL_INTERNAL_STAGE/order_items.csv'
FILE_FORMAT = UTIL.CSV_FORMAT
ON_ERROR = CONTINUE;

COPY INTO RAW.RAW_USER_ACTIVITY
FROM '@UTIL.RETAIL_INTERNAL_STAGE/user_activity.csv'
FILE_FORMAT = UTIL.CSV_FORMAT
ON_ERROR = CONTINUE;

CREATE OR REPLACE STREAM RAW.CUSTOMERS_STREAM ON TABLE RAW.RAW_CUSTOMERS;
CREATE OR REPLACE STREAM RAW.PRODUCTS_STREAM ON TABLE RAW.RAW_PRODUCTS;
CREATE OR REPLACE STREAM RAW.ORDERS_STREAM ON TABLE RAW.RAW_ORDERS;
CREATE OR REPLACE STREAM RAW.ORDER_ITEMS_STREAM ON TABLE RAW.RAW_ORDER_ITEMS;
CREATE OR REPLACE STREAM RAW.USER_ACTIVITY_STREAM ON TABLE RAW.RAW_USER_ACTIVITY;

select * from raw.RAW_ORDER_ITEMS;
select * from RAW.RAW_PRODUCTS;
select * from RAW.RAW_USER_ACTIVITY;
select * from RAW.RAW_ORDERS;
select * from RAW.RAW_CUSTOMERS;

select * from RAW.USER_ACTIVITY_STREAM;
select * from RAW.PRODUCTS_STREAM;
select * from RAW.CUSTOMERS_STREAM;
select * from RAW.ORDERS_STREAM;
select * from RAW.ORDER_ITEMS_STREAM;


TRUNCATE TABLE RAW.RAW_CUSTOMERS;
TRUNCATE TABLE RAW.RAW_PRODUCTS;
TRUNCATE TABLE RAW.RAW_ORDERS;
TRUNCATE TABLE RAW.RAW_ORDER_ITEMS;
TRUNCATE TABLE RAW.RAW_USER_ACTIVITY;
USE DATABASE RETAIL_COMPANY;

USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE FILE FORMAT UTIL.CSV_FORMAT
TYPE = CSV
SKIP_HEADER = 1
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
TRIM_SPACE = TRUE
NULL_IF = ('NULL','null','N/A','',' ');

CREATE OR REPLACE STAGE UTIL.RETAIL_INTERNAL_STAGE
FILE_FORMAT = UTIL.CSV_FORMAT;

CREATE OR REPLACE TABLE RAW.RAW_CUSTOMERS (
    CUSTOMER_ID STRING,
    NAME STRING,
    CITY STRING,
    SIGNUP_DATE STRING,
    LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.RAW_PRODUCTS (
    PRODUCT_ID STRING,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    PRICE STRING,
    LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.RAW_ORDERS (
    ORDER_ID STRING,
    CUSTOMER_ID STRING,
    ORDER_DATE STRING,
    TOTAL_AMOUNT STRING,
    LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.RAW_ORDER_ITEMS (
    ORDER_ITEM_ID STRING,
    ORDER_ID STRING,
    PRODUCT_ID STRING,
    QUANTITY STRING,
    LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE RAW.RAW_USER_ACTIVITY (
    ACTIVITY_ID STRING,
    CUSTOMER_ID STRING,
    ACTIVITY_TYPE STRING,
    ACTIVITY_TIME STRING,
    LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP()
);
COPY INTO RAW.RAW_CUSTOMERS
FROM '@UTIL.RETAIL_INTERNAL_STAGE/customers.csv'
FILE_FORMAT = UTIL.CSV_FORMAT
ON_ERROR = CONTINUE;

COPY INTO RAW.RAW_PRODUCTS
FROM '@UTIL.RETAIL_INTERNAL_STAGE/products.csv'
FILE_FORMAT = UTIL.CSV_FORMAT
ON_ERROR = CONTINUE;

COPY INTO RAW.RAW_ORDERS
FROM '@UTIL.RETAIL_INTERNAL_STAGE/orders.csv'
FILE_FORMAT = UTIL.CSV_FORMAT
ON_ERROR = CONTINUE;

COPY INTO RAW.RAW_ORDER_ITEMS
FROM '@UTIL.RETAIL_INTERNAL_STAGE/order_items.csv'
FILE_FORMAT = UTIL.CSV_FORMAT
ON_ERROR = CONTINUE;

COPY INTO RAW.RAW_USER_ACTIVITY
FROM '@UTIL.RETAIL_INTERNAL_STAGE/user_activity.csv'
FILE_FORMAT = UTIL.CSV_FORMAT
ON_ERROR = CONTINUE;

CREATE OR REPLACE STREAM RAW.CUSTOMERS_STREAM ON TABLE RAW.RAW_CUSTOMERS;
CREATE OR REPLACE STREAM RAW.PRODUCTS_STREAM ON TABLE RAW.RAW_PRODUCTS;
CREATE OR REPLACE STREAM RAW.ORDERS_STREAM ON TABLE RAW.RAW_ORDERS;
CREATE OR REPLACE STREAM RAW.ORDER_ITEMS_STREAM ON TABLE RAW.RAW_ORDER_ITEMS;
CREATE OR REPLACE STREAM RAW.USER_ACTIVITY_STREAM ON TABLE RAW.RAW_USER_ACTIVITY;

select * from raw.RAW_ORDER_ITEMS;
select * from RAW.RAW_PRODUCTS;
select * from RAW.RAW_USER_ACTIVITY;
select * from RAW.RAW_ORDERS;
select * from RAW.RAW_CUSTOMERS;

select * from RAW.USER_ACTIVITY_STREAM;
select * from RAW.PRODUCTS_STREAM;
select * from RAW.CUSTOMERS_STREAM;
select * from RAW.ORDERS_STREAM;
select * from RAW.ORDER_ITEMS_STREAM;


TRUNCATE TABLE RAW.RAW_CUSTOMERS;
TRUNCATE TABLE RAW.RAW_PRODUCTS;
TRUNCATE TABLE RAW.RAW_ORDERS;
TRUNCATE TABLE RAW.RAW_ORDER_ITEMS;
TRUNCATE TABLE RAW.RAW_USER_ACTIVITY;
