USE DATABASE RETAIL_COMPANY;

USE ROLE VALIDATED_LAYER_ROLE;

USE SCHEMA VALIDATED;

CREATE OR REPLACE TABLE CONTROL.ERROR_LOG (
    TABLE_NAME STRING,
    ERROR_TYPE STRING,
    RECORD_DATA VARIANT,
    ERROR_TIME TIMESTAMP
);

CREATE OR REPLACE TABLE VALIDATED.CUSTOMERS (
    CUSTOMER_ID STRING,
    NAME STRING,
    CITY STRING,
    SIGNUP_DATE DATE
);

CREATE OR REPLACE TABLE VALIDATED.PRODUCTS (
    PRODUCT_ID STRING,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    PRICE NUMBER(10,2)
);

CREATE OR REPLACE TABLE VALIDATED.ORDERS (
    ORDER_ID STRING,
    CUSTOMER_ID STRING,
    ORDER_DATE DATE,
    TOTAL_AMOUNT NUMBER(10,2)
);

CREATE OR REPLACE TABLE VALIDATED.ORDER_ITEMS (
    ORDER_ITEM_ID STRING,
    ORDER_ID STRING,
    PRODUCT_ID STRING,
    QUANTITY NUMBER
);

CREATE OR REPLACE TABLE VALIDATED.USER_ACTIVITY (
    ACTIVITY_ID STRING,
    CUSTOMER_ID STRING,
    ACTIVITY_TYPE STRING,
    ACTIVITY_TIME TIMESTAMP
);


CREATE OR REPLACE PROCEDURE VALIDATED.SP_CLEAN_RETAIL_STREAM()
RETURNS STRING
LANGUAGE SQL
AS
$$
BEGIN

    CREATE OR REPLACE TEMP TABLE CUR_CUSTOMERS AS
    SELECT * FROM RAW.CUSTOMERS_STREAM
    WHERE METADATA$ACTION = 'INSERT';

    INSERT INTO CONTROL.ERROR_LOG
    SELECT 'CUSTOMERS','INVALID_DATA',OBJECT_CONSTRUCT(*),CURRENT_TIMESTAMP
    FROM CUR_CUSTOMERS
    WHERE CUSTOMER_ID IS NULL
       OR NAME IS NULL
       OR CITY IS NULL
       OR SIGNUP_DATE IS NULL
       OR TRY_TO_DATE(SIGNUP_DATE,'YYYY-MM-DD') IS NULL;

    MERGE INTO VALIDATED.CUSTOMERS tgt
    USING (
        SELECT *
        FROM (
            SELECT
                CUSTOMER_ID,
                INITCAP(NAME) AS NAME,
                INITCAP(CITY) AS CITY,
                TRY_TO_DATE(SIGNUP_DATE,'YYYY-MM-DD') AS SIGNUP_DATE,
                ROW_NUMBER() OVER(PARTITION BY CUSTOMER_ID ORDER BY LOAD_TS DESC) AS RN
            FROM CUR_CUSTOMERS
            WHERE CUSTOMER_ID IS NOT NULL
              AND NAME IS NOT NULL
              AND CITY IS NOT NULL
              AND TRY_TO_DATE(SIGNUP_DATE,'YYYY-MM-DD') IS NOT NULL
        )
        WHERE RN = 1
    ) src
    ON tgt.CUSTOMER_ID = src.CUSTOMER_ID
    WHEN MATCHED THEN UPDATE SET
        tgt.NAME = src.NAME,
        tgt.CITY = src.CITY,
        tgt.SIGNUP_DATE = src.SIGNUP_DATE
    WHEN NOT MATCHED THEN INSERT VALUES (
        src.CUSTOMER_ID,
        src.NAME,
        src.CITY,
        src.SIGNUP_DATE
    );

    CREATE OR REPLACE TEMP TABLE CUR_PRODUCTS AS
    SELECT * FROM RAW.PRODUCTS_STREAM
    WHERE METADATA$ACTION = 'INSERT';

    INSERT INTO CONTROL.ERROR_LOG
    SELECT 'PRODUCTS','INVALID_DATA',OBJECT_CONSTRUCT(*),CURRENT_TIMESTAMP
    FROM CUR_PRODUCTS
    WHERE PRODUCT_ID IS NULL
       OR PRODUCT_NAME IS NULL
       OR CATEGORY IS NULL
       OR TRY_TO_NUMBER(PRICE) IS NULL
       OR TRY_TO_NUMBER(PRICE) <= 0;

    MERGE INTO VALIDATED.PRODUCTS tgt
    USING (
        SELECT *
        FROM (
            SELECT
                PRODUCT_ID,
                INITCAP(PRODUCT_NAME) AS PRODUCT_NAME,
                INITCAP(CATEGORY) AS CATEGORY,
                TRY_TO_NUMBER(PRICE) AS PRICE,
                ROW_NUMBER() OVER(PARTITION BY PRODUCT_ID ORDER BY LOAD_TS DESC) AS RN
            FROM CUR_PRODUCTS
            WHERE PRODUCT_ID IS NOT NULL
              AND PRODUCT_NAME IS NOT NULL
              AND CATEGORY IS NOT NULL
              AND TRY_TO_NUMBER(PRICE) > 0
        )
        WHERE RN = 1
    ) src
    ON tgt.PRODUCT_ID = src.PRODUCT_ID
    WHEN MATCHED THEN UPDATE SET
        tgt.PRODUCT_NAME = src.PRODUCT_NAME,
        tgt.CATEGORY = src.CATEGORY,
        tgt.PRICE = src.PRICE
    WHEN NOT MATCHED THEN INSERT VALUES (
        src.PRODUCT_ID,
        src.PRODUCT_NAME,
        src.CATEGORY,
        src.PRICE
    );

    CREATE OR REPLACE TEMP TABLE CUR_ORDERS AS
    SELECT * FROM RAW.ORDERS_STREAM
    WHERE METADATA$ACTION = 'INSERT';

    INSERT INTO CONTROL.ERROR_LOG
    SELECT 'ORDERS','INVALID_DATA',OBJECT_CONSTRUCT(*),CURRENT_TIMESTAMP
    FROM CUR_ORDERS
    WHERE ORDER_ID IS NULL
       OR CUSTOMER_ID IS NULL
       OR TRY_TO_DATE(ORDER_DATE,'YYYY-MM-DD') IS NULL
       OR TRY_TO_NUMBER(TOTAL_AMOUNT) IS NULL
       OR TRY_TO_NUMBER(TOTAL_AMOUNT) <= 0;

    MERGE INTO VALIDATED.ORDERS tgt
    USING (
        SELECT *
        FROM (
            SELECT
                ORDER_ID,
                CUSTOMER_ID,
                TRY_TO_DATE(ORDER_DATE,'YYYY-MM-DD') AS ORDER_DATE,
                TRY_TO_NUMBER(TOTAL_AMOUNT) AS TOTAL_AMOUNT,
                ROW_NUMBER() OVER(PARTITION BY ORDER_ID ORDER BY LOAD_TS DESC) AS RN
            FROM CUR_ORDERS
            WHERE ORDER_ID IS NOT NULL
              AND CUSTOMER_ID IS NOT NULL
              AND TRY_TO_DATE(ORDER_DATE,'YYYY-MM-DD') IS NOT NULL
              AND TRY_TO_NUMBER(TOTAL_AMOUNT) > 0
        )
        WHERE RN = 1
    ) src
    ON tgt.ORDER_ID = src.ORDER_ID
    WHEN MATCHED THEN UPDATE SET
        tgt.CUSTOMER_ID = src.CUSTOMER_ID,
        tgt.ORDER_DATE = src.ORDER_DATE,
        tgt.TOTAL_AMOUNT = src.TOTAL_AMOUNT
    WHEN NOT MATCHED THEN INSERT VALUES (
        src.ORDER_ID,
        src.CUSTOMER_ID,
        src.ORDER_DATE,
        src.TOTAL_AMOUNT
    );

    CREATE OR REPLACE TEMP TABLE CUR_ORDER_ITEMS AS
    SELECT * FROM RAW.ORDER_ITEMS_STREAM
    WHERE METADATA$ACTION = 'INSERT';

    INSERT INTO CONTROL.ERROR_LOG
    SELECT 'ORDER_ITEMS','INVALID_DATA',OBJECT_CONSTRUCT(*),CURRENT_TIMESTAMP
    FROM CUR_ORDER_ITEMS
    WHERE ORDER_ITEM_ID IS NULL
       OR ORDER_ID IS NULL
       OR PRODUCT_ID IS NULL
       OR TRY_TO_NUMBER(QUANTITY) IS NULL
       OR TRY_TO_NUMBER(QUANTITY) <= 0;

    MERGE INTO VALIDATED.ORDER_ITEMS tgt
    USING (
        SELECT *
        FROM (
            SELECT
                ORDER_ITEM_ID,
                ORDER_ID,
                PRODUCT_ID,
                TRY_TO_NUMBER(QUANTITY) AS QUANTITY,
                ROW_NUMBER() OVER(PARTITION BY ORDER_ITEM_ID ORDER BY LOAD_TS DESC) AS RN
            FROM CUR_ORDER_ITEMS
            WHERE ORDER_ITEM_ID IS NOT NULL
              AND ORDER_ID IS NOT NULL
              AND PRODUCT_ID IS NOT NULL
              AND TRY_TO_NUMBER(QUANTITY) > 0
        )
        WHERE RN = 1
    ) src
    ON tgt.ORDER_ITEM_ID = src.ORDER_ITEM_ID
    WHEN MATCHED THEN UPDATE SET
        tgt.ORDER_ID = src.ORDER_ID,
        tgt.PRODUCT_ID = src.PRODUCT_ID,
        tgt.QUANTITY = src.QUANTITY
    WHEN NOT MATCHED THEN INSERT VALUES (
        src.ORDER_ITEM_ID,
        src.ORDER_ID,
        src.PRODUCT_ID,
        src.QUANTITY
    );

    CREATE OR REPLACE TEMP TABLE CUR_ACTIVITY AS
    SELECT * FROM RAW.USER_ACTIVITY_STREAM
    WHERE METADATA$ACTION = 'INSERT';

    INSERT INTO CONTROL.ERROR_LOG
    SELECT 'USER_ACTIVITY','INVALID_DATA',OBJECT_CONSTRUCT(*),CURRENT_TIMESTAMP
    FROM CUR_ACTIVITY
    WHERE ACTIVITY_ID IS NULL
       OR CUSTOMER_ID IS NULL
       OR ACTIVITY_TYPE IS NULL
       OR TRY_TO_TIMESTAMP(ACTIVITY_TIME) IS NULL;

    MERGE INTO VALIDATED.USER_ACTIVITY tgt
    USING (
        SELECT *
        FROM (
            SELECT
                ACTIVITY_ID,
                CUSTOMER_ID,
                UPPER(ACTIVITY_TYPE) AS ACTIVITY_TYPE,
                TRY_TO_TIMESTAMP(ACTIVITY_TIME) AS ACTIVITY_TIME,
                ROW_NUMBER() OVER(PARTITION BY ACTIVITY_ID ORDER BY LOAD_TS DESC) AS RN
            FROM CUR_ACTIVITY
            WHERE ACTIVITY_ID IS NOT NULL
              AND CUSTOMER_ID IS NOT NULL
              AND ACTIVITY_TYPE IS NOT NULL
              AND TRY_TO_TIMESTAMP(ACTIVITY_TIME) IS NOT NULL
        )
        WHERE RN = 1
    ) src
    ON tgt.ACTIVITY_ID = src.ACTIVITY_ID
    WHEN MATCHED THEN UPDATE SET
        tgt.CUSTOMER_ID = src.CUSTOMER_ID,
        tgt.ACTIVITY_TYPE = src.ACTIVITY_TYPE,
        tgt.ACTIVITY_TIME = src.ACTIVITY_TIME
    WHEN NOT MATCHED THEN INSERT VALUES (
        src.ACTIVITY_ID,
        src.CUSTOMER_ID,
        src.ACTIVITY_TYPE,
        src.ACTIVITY_TIME
    );

    RETURN 'RETAIL STREAM DATA CLEANED SUCCESSFULLY';

END;
$$;


CALL VALIDATED.SP_CLEAN_RETAIL_STREAM();

SELECT * FROM VALIDATED.ORDER_ITEMS;
SELECT * FROM VALIDATED.CUSTOMERS;
SELECT * FROM VALIDATED.PRODUCTS;
SELECT * FROM VALIDATED.ORDERS;
SELECT * FROM VALIDATED.USER_ACTIVITY;

SELECT * FROM CONTROL.ERROR_LOG;
